export const FIND_STORES = "FIND_STORES";
export const LOAD_STORES_SUCCESS = "LOAD_STORES_SUCCESS";
export const LOAD_CITIES_SUCCESS = "LOAD_CITIES_SUCCESS";
export const LOAD_STREETS_SUCCESS = "LOAD_STREETS_SUCCESS";
export const LOAD_CITIES = "LOAD_CITIES";
export const LOAD_STREETS = "LOAD_STREETS";
